name: OpenReview-js Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  repository_dispatch:
    types: [openreview-api-updated]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 7.0
          mongodb-replica-set: rs0
      - name: Configure sysctl Limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
      - name: Checkout openreview-py
        uses: actions/checkout@v4
        with:
          repository: openreview/openreview-py
          path: openreview-py
      - name: Checkout openreview-api
        uses: actions/checkout@v4
        with:
          repository: openreview/openreview-api
          token: ${{ secrets.PAT_OPENREVIEW_IESL }}
          path: openreview-api
      - name: Checkout openreview-js
        uses: actions/checkout@v4
        with:
          path: openreview-js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            openreview-api/package-lock.json
            openreview-js/package-lock.json
      - name: Setup openreview-py
        run: |
          cd openreview-py
          python -m pip install --upgrade pip
          pip install -e .
      - name: Setup openreview-api
        run: |
          cd openreview-api
          mkdir -p logs files/attachments files/pdfs files/temp
          sudo apt-get install -y chromium-suid-sandbox
          sudo chmod 4755 /usr/lib/chromium/chrome-sandbox
          export PUPPETEER_SKIP_DOWNLOAD='true'
          npm ci
      - name: Run openreview-api
        run: |
          cd openreview-api
          npm run cleanStartJS &
      - name: Run Tests
        run: |
          cd openreview-js
          npm run coverage
